### ISSUE TITLE
Set up this repository with development environment

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/data-viewer#1]
🎉 🎉  Let's get this party started! 🎉 🎉 

(I'm trying to capture some of the thoughts from a kickoff conversation with @reefdog here!)

This will be a TypeScript project; the frontend framework is TBD but may likely be Svelte.

This issue is intended to capture the need for:

1. Setting up the dev environment with default documentation and tooling (e.g. running the sveltekit app installer).
2. Making modifications to things like linting rules, code coverage expectations, etc based on this specific project.
3. Documenting the intended code structure.

**Comment by reefdog** [comment]
I'm currently exploring [SvelteKit](https://kit.svelte.dev/). Never used it, but I've tinkered with [Svelte](https://svelte.dev/) and appreciate its pitch (reactive framework that builds down to vanilla JS/HTML/CSS with no virtual DOM) and SvelteKit seems to add all the remaining niceties for a full front-end framework.

Before I get any farther, are the following components compliant with our licensing needs? The Required ones are, well, required for using SvelteKit. The optional ones are recommended by SvelteKit when running the initial setup.

| Component | Role | Required? | License |
| :-------- | :--- | :-------- | :------ |
| [Svelte](https://svelte.dev/) | Framework | Required | [MIT](https://github.com/sveltejs/svelte/blob/master/LICENSE.md) |
| [SvelteKit](https://kit.svelte.dev/) | Framework | Required | [MIT](https://github.com/sveltejs/kit/blob/master/LICENSE) |
| [Vite](https://vitejs.dev/) | Tooling that SvelteKit depends on | Required | [MIT](https://github.com/vitejs/vite/blob/main/LICENSE) |
| [ESLint](https://eslint.org/) | Linting | Optional | [MIT](https://github.com/eslint/eslint/blob/main/LICENSE) |
| [Prettier](https://prettier.io/) | Code formatting | Optional | [MIT](https://github.com/prettier/prettier/blob/main/LICENSE) |
| [Playwright](https://playwright.dev/) | Automated browser testing | Optional | [Apache 2.0](https://github.com/microsoft/playwright/blob/main/LICENSE) |
| [Vitest](https://vitest.dev/) | Unit testing | Optional | [MIT](https://github.com/vitest-dev/vitest/blob/main/LICENSE) |

**Comment by reefdog** [comment]
Per a conversation with @jasonaowen, we're going with React. We're all curious about Svelte but lack experience, and don't have time to get experience on the job. React is a sensible choice given its popularity in front-end development and the team's history with it.

**Comment by slifty** [comment]
@jasonaowen just a heads up: where appropriate I'd recommend using a similar stack to what we have in the service repository (which will hopefully be quite familiar!)

**Comment by jasonaowen** [comment]
@slifty of course! Is there anything in particular you're thinking of?
