### ISSUE TITLE
Show message on "no results" searches

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/data-viewer#115]
When someone searches for something and the search succeeds with no results - that is, when no proposals match the search query - we will display an empty list. Instead, we should display a message indicating that no results were returned.

Figure out what to display, and show it when there are no results.

Note that this message is likely to also be displayed on new instances of the API, before proposals are loaded. That is primarily going to be a dev issue, so we do not necessarily need to handle it as part of this, but I mention it in case that informs the design.

**Comment by jasonaowen** [comment]
A lot of the [search UX best practices](https://www.uxbooth.com/articles/best-practices-for-search/) articles I found emphasize that a "no results" page can be a dead end for a user, and suggest things ranging from popular searches to promoted products; since this is not an ecommerce platform, I'm not sure how many of those recommendations are relevant. Still, interesting reading.

**Comment by reefdog** [comment]
@jasonaowen I think you bring up a good point about the best UX giving users something to do next, but I think in our case I can't imagine when we'd get to this level of optimization. I'm going to close this and we can re-open or open a new ticket if users are suffering.
