### ISSUE TITLE
Choose default fields for proposal lists

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#13]
We need to choose the set of default canonical fields we use when listing proposals in wide table view, as well as the preferred order of the fields:

<img width="1512" alt="PDC Data Viewer 01 - Proposals Table" src="https://user-images.githubusercontent.com/4731/220751445-2701db4c-16d0-4e3b-83ce-df2b575f6f57.png">

And in the condensed sidebar card view:
<img width="1512" alt="PDC Data Viewer 02 - Proposal" src="https://user-images.githubusercontent.com/4731/220751450-d328b240-42f7-41fe-a1dd-887f3318edd9.png">

This is an operations / data decision, not a technical one, so I'm assigning it to @jim-mcgowan to do or triage.

**Comment by jim-mcgowan** [comment]
@reefdog: I recommend the following fields (columns) to start:

- Organization Name
- Organization Tax ID
- Organization City (Could be combined with State/Province, Country)
- Organization State/Province
- Organization Country
- Organization Website
- Organization Mission Statement
- Organization Start Date
- Organization Operating Budget
- Proposal Name
- Proposal Summary
- Proposal Amount Requested
- Proposal Budget
- Proposal Fiscal Sponsor Name
- Proposal Start Date
- Proposal End Date
- Proposal Location of Work

**Comment by reefdog** [comment]
Super, thanks!

> (Could be combined with State/Province, Country)

Opinion: in **table views**, we shouldn't combine / concatenate / humanize values. We should present them literally: "this field contains this value".

**Layout view**, however, will be a great place for this. The curated interface makes no implicit commitment that you're looking at `field:value` pairs. It's not just about rearranging the data, but demonstrating how useful and friendly it can be when predictable.

**Comment by reefdog** [comment]
Oops, @jim-mcgowan I closed too early.

I could also use a recommendation for which fields we should use to compose the sidebar cards for each proposal. Implicit in my design (but quickly/thoughtlessly chosen) were:

- Proposal Name
- Organization Name
- Organization City
- Organization State/Province
- Organization Country

And then a date and status that don't really have a purpose.

Can you make a recommendation for composing that little card, too?

**Comment by jim-mcgowan** [comment]
@reefdog:

Yes, but in this order:

- Organization Name
- Organization City, Organization State/Province, Organization Country
- Proposal Name
