### ISSUE TITLE
Create proposal detail page

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#19]
Users should be able to visit a detail page for an individual proposal, listing all the proposal's canonical fields and more recent values:

<img width="1512" alt="PDC Data Viewer 02 - Proposal" src="https://user-images.githubusercontent.com/4731/220751450-d328b240-42f7-41fe-a1dd-887f3318edd9.png">

The page should at least extract the proposal title, applicant name/EID, and data source into the pre-table UI. Also, a toggle for word-wrapping long cells should be present (see multi-bar icon in the right of the Version 4 header).

The proposal list in the sidebar will be the same state and content as the [table view](https://github.com/PhilanthropyDataCommons/data-viewer/issues/14), but condensed to the sidebar. (I may split this off to a separate task.)

Several features shown in the mockup will be delivered as separate tasks, e.g. [version history](https://github.com/PhilanthropyDataCommons/data-viewer/issues/22) and [key](https://github.com/PhilanthropyDataCommons/data-viewer/issues/20)/[source](https://github.com/PhilanthropyDataCommons/data-viewer/issues/21) toggles.

**Comment by reefdog** [comment]
@jasonaowen I would advocate for closing this issue and opening up any remaining tasks and features as separate issues.

**Comment by jasonaowen** [comment]
I agree!
