### ISSUE TITLE
Prevent search engines from indexing error pages

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/data-viewer#31]
In https://github.com/PhilanthropyDataCommons/data-viewer/pull/29#discussion_r1128267978, @reefdog wrote:

> ...our 404 page returns an HTTP 200 status code. ... I sure wish we could respond with true 404s.
> 
> Semantics aside, a practical reason to respond with a true 404 is to signal search engines that the URL isn't found / shouldn't be indexed. Even though we're currently private, I think we should assume some day we may serve _some_ public pages and prevent `/anything-i-dream-up-and-link-to-or-submit-to-an-index-maliciously` from being indexed.
> 
> Could you add a [`noindex` meta tag](https://developers.google.com/search/docs/crawling-indexing/block-indexing) to the 404 page?

**Comment by reefdog** [comment]
My suggestion here, predicated on our pages eventually being able to write to the `<head>` through some mechanism like [Gatsby's Head API](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/), is that our [`NotFound` page](https://github.com/PhilanthropyDataCommons/data-viewer/blob/main/src/NotFound.tsx) write `<meta name="robots" content="noindex">` to the `<head>`. This way, even if we relax our `robots.txt` rule, any time our app serves this `NotFound` page, it will also have added this `noindex` rule.

**Comment by reefdog** [comment]
I used too many commas in that post. I, am, sorry.
