### ISSUE TITLE
Can we use Source Sans Pro?

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#37]
Discussion time!

I designed our mockup UI with the [Source Sans Pro](https://fonts.google.com/specimen/Source+Sans+Pro/about) typeface. After considering not using a webfont at all, I decided it's worthwhile for style and layout. But, I want to make sure we're okay with it!

- It's licensed under the [Open Font License](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL), which I believe is compatible with our use.
- Rather than load the font from Google, we'd download the files and serve them directly ourselves.

Any objections or additional thoughts?

**Comment by jasonaowen** [comment]
Policy wise, I have no concerns - I hadn't heard of the Open Font License before, but the [OFL Wikipedia article](https://en.wikipedia.org/wiki/SIL_Open_Font_License) is fairly glowing, and if [Debian is cool with the OFL](https://wiki.debian.org/DFSGLicenses#The_SIL_Open_Font_License), then I definitely am!

(cc @kfogel, in case you want to weigh in, but I don't propose to block on you - if you disagree with this stance we can back out changes later!)

Implementation-wise, it looks like [Fontsource](https://fontsource.org/) has an [npm package for Source Sans Pro](https://www.npmjs.com/package/@fontsource/source-sans-pro). @reefdog if those instructions make sense, try them and see if it works as you'd hope? That'd save us from vendoring third-party content and adding build artifacts to our repo!

**Comment by reefdog** [comment]
Great find! I'll give it a try.

**Comment by kfogel** [comment]
+1 here.

**Comment by jasonaowen** [comment]
Great! Thanks, @jim-mcgowan and @kfogel.
