### ISSUE TITLE
Add changelog / What's New page

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#39]
Jim has requested a page on which we can communicate to Pilot participants what's new / what's changed.

Eventually, this will probably have to be a bbbbbblog, but it will start as a static page whose contents have to be updated manually (and as HTML unless Markdown comes "free").

**Comment by jasonaowen** [comment]
Before we start talking about tooling, do you / @jim-mcgowan think a link from `pilot.pdco` to `github/.../CHANGELOG.md` would be good enough?

**Comment by jasonaowen** [comment]
Here is an example changelog from one of our dependencies: https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md . Its target audience is developers, so of course the *content* is technical, but it's just markdown - we could of course pitch the tone of our writing to be less technical. How does that interface look to you?

**Comment by jim-mcgowan** [comment]
@jasonaowen I think it can work. The goal is to keep participants engaged over the next two months and allow them to see for themselves the regular and incremental progress being made. This will hopefully encourage them to keep logging in to watch the PDC evolve.

**Comment by jasonaowen** [comment]
The best code is the code we don't write!

**Comment by reefdog** [comment]
@jasonaowen What do you think our changelog format should be? I'm familiar with [Common Changelog](https://common-changelog.org/), and I like it as a starting point, but we aren't really changelogging releases, and I'm not sure the Changed/Fixed/Added type breakdown makes a ton of sense for us.

Our target audience for this is non-developer stakeholders. Which means we're perhaps misusing the `CHANGELOG` name and should come up with another one?

I'm thinking of a format something like:

```
# Title of the document

## Milestone date

- List
- Of
- Accomplishments

## Milestone date

- List
- Of
- Accomplishments
```

**Comment by jasonaowen** [comment]
We discussed this on our team call today. Thank you @reefdog for taking notes!

- @kfogel suggests `RECENT_CHANGES` (over the overloaded name `CHANGELOG`)
- Contains user-facing changes (or anything that affects the user experience — including service changes that we can explain to users how it affects them) (please excuse the convoluted phrasing)
- @kfogel +1s the suggested format
- "What makes the list?"
  - User-visible changes / changes to the user experience
  - Can include service repo changes, e.g. performance improvements
  - Append with "major/minor"
  - "Use your judgment"
- Linked from landing page (where GitHub contribution used to be)
  - Sans GitHub name — no need to market the platform
- @kfogel notes that the landing page, accessible only from the logo, isn't discoverable after login and if we expect people to want to access things like Recent Changes after login, we should either provide a more discoverable link back to the landing page or add an About page. (@jasonaowen suggests footer links potentially.)
