### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/data-viewer#48]
I think we will want a landing page for logged-out users to see. Currently, we're still showing the React logo and a few PDC links. Soon we will have the option of showing the proposals list (#14) in the root, which would require logging in immediately. I think it's worthwhile to have a brief landing page that would introduce the project and maintain the links we currently have.

**Comment by reefdog** [comment]
Agree! Propose we show the screens below. After logging in the user would be taken directly to the Dashboard, but if they manually backed out to the root they would see the slightly customized version.

Default:
![Landing](https://user-images.githubusercontent.com/4731/230509806-42a56a44-99b1-41fc-979c-ed5998ce99a4.png)

Logged in:
![Landing](https://user-images.githubusercontent.com/4731/230510438-6e4f07ca-aec1-47bd-95ae-0d9cfccb3e01.png)

**Comment by reefdog** [comment]
I would need copy for the page. I suggest we keep it exceptionally to the point as shown, but include:

- Brief few sentences about this being a pilot view of the data
- Link to the [main marketing site](https://philanthropydatacommons.org/)
- Log in call to action
- Instructions for emailing Jim (or whoever) for an account
- Contact email address
- Code contribution links

**Comment by jasonaowen** [comment]
Love it!

I don't think the "You are logged in as <name>." line adds much, and can be cut.

What do you think of reusing the document icon from the top bar dashboard link in the CTA dashboard link?

**Comment by reefdog** [comment]
@jasonaowen Great idea. Also Jim says too much text and to deemphasize the GitHub stuff. New versions below. Bear in mind this is a replacement for our current spinning React logo. This is not the end-all best landing page we can imagine. :)

<img width="1512" alt="Landing" src="https://user-images.githubusercontent.com/4731/230516466-5e6686ed-fcfc-4596-9564-f45e34ca3cea.png">

<img width="1512" alt="Landing - Logged In" src="https://user-images.githubusercontent.com/4731/230516465-7c7fa40d-0e5d-4ad9-baa7-8e9266d8a807.png">

**Comment by jasonaowen** [comment]
Awesome!
