### ISSUE TITLE
Session timeout experience needs improvement

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#50]
See #51 for an session timeout experience that occurred. The experience could have been improved in a few ways:

1. Wrap the error in our interface.
2. Give the user a call to action to resolve: either provide a link to the login form, or send them directly there instead of to this intermediate error page. The latter would necessitate customizing the login page with a contextually-appropriate message so they know why they're there.
4. Be sure after resolving (re-authenticating) they are sent back to where they were.
5. I'm torn on if we _should_ boot the user the moment their token expires (versus if they just try to load a new page/data with an expired token). For security, it's nice to boot them right away, kind of like the OS locking your screen after some idle time. The experience, though, of non-interactively looking at a page and having it suddenly boot you is… abrupt. I'm leaning toward the secure part, though, and that our token refresh system will keep extending that timeout.

I'm assigning this ticket broadly so we can discuss what disparate components of the system require change.

**Comment by jasonaowen** [comment]
1. The [@axa-fr/react-oidc library](https://github.com/AxaFrance/react-oidc/) does [provide some options here](https://github.com/AxaFrance/react-oidc/blob/9b791fa219a0795abb6b52515453428bd6562d51/packages/react/src/oidc/OidcProvider.tsx#L19)! We can provide a custom component to replace the default `SessionLost` component we see now. If you want to design something, @reefdog, I can wire it up! As an aside, there are other [default components](https://github.com/AxaFrance/react-oidc/tree/master/packages/react/src/oidc/core/default-component) we should probably replace.
2. The error page should explain what happened, and include a call to action ("click the login button to continue"), but I don't think it should automatically redirect to our IdP.
3. We should have this out-of-the-box already!
4. This is the default behavior, and I'd lean towards maintaining it. Again, this shouldn't happen very often under normal circumstances!

**Comment by reefdog** [comment]
Oh, that's great, thank you! I'm going to create two new issues for 1 and 2, happy that 3 and 4 are good to go.

**Comment by reefdog** [comment]
#57 and #58 opened, closing this one.
