### ISSUE TITLE
Hide authenticated links when not logged in

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#60]
When logged in, only the login link should be visible in the navbar. Hide the rest.

**Comment by jasonaowen** [comment]
Are the links sensitive information? The code is open source, and the pages are being rendered by the browser, so I hope not. The current behavior is that clicking any authenticated link will bounce through the login flow, so the login button becomes somewhat extraneous. Can you say more about why you want this?

**Comment by reefdog** [comment]
It's a good question and is giving me some great food for thought.

I do want users to feel in control. If they see a Dashboard link, click it, and get bounced through login, is that better or worse than not seeing it until logging in? 🤔

Thinking through this, you've convinced me! I was on design autopilot.

**Comment by reefdog** [comment]
That same logic applies, come to think of it, to the landing page. I think I can coerce the copy and design to a single consistent design.
