### ISSUE TITLE
Use `/proposals/{id}` instead of `/proposal/{id}` for proposal detail URL

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#63]
Could we change our individual proposal routes to `/proposals/{id}`?

I know that's not as semantically defensible, but it seems to be more idiomatic (see: GitHub's `/issues/{id}`, StackOverflow's `/questions/{id}`) and ergonomic (go between the index and the individual just by the presence or absence of an ID).

Here's a [good SO discussion](https://stackoverflow.com/questions/6845772/should-i-use-singular-or-plural-name-convention-for-rest-resources) about it. The accepted answer promotes our current syntax, but by far the one with the most votes promotes the Railsy, all-plural form. The electoral college strikes again!

I tested it and it works (including still supporting our query params on the index page). The diff is simple:

```diff
diff --git a/src/App.tsx b/src/App.tsx
index 1e41341..53944e2 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -13,7 +13,7 @@ const App = () => (
     <main className="App-main">
       <Routes>
         <Route path="/" element={<Placeholder />} />
-        <Route path="/proposal/:proposalId" element={<ProposalDetail />} />
+        <Route path="/proposals/:proposalId" element={<ProposalDetail />} />
         <Route path="/proposals" element={<ProposalListPage />} />
         <Route path="*" element={<NotFound />} />
       </Routes>
diff --git a/src/components/ProposalDetailPanel.tsx b/src/components/ProposalDetailPanel.tsx
index 91a9111..cf2c957 100644
--- a/src/components/ProposalDetailPanel.tsx
+++ b/src/components/ProposalDetailPanel.tsx
@@ -58,14 +58,14 @@ const ProposalDetailPanel = ({
         {process.env.NODE_ENV !== 'production' && (
           <>
             <Link
-              to={`/proposal/${proposalId - 1}`}
+              to={`/proposals/${proposalId - 1}`}
               className="button button--color-gray"
             >
               <BackwardIcon className="icon" />
               Previous
             </Link>
             <Link
-              to={`/proposal/${proposalId + 1}`}
+              to={`/proposals/${proposalId + 1}`}
               className="button button--color-gray"
             >
               Next
diff --git a/src/components/ProposalListTable.tsx b/src/components/ProposalListTable.tsx
index f0b661e..2f991f6 100644
--- a/src/components/ProposalListTable.tsx
+++ b/src/components/ProposalListTable.tsx
@@ -24,7 +24,7 @@ const ProposalListTableRow = ({
   const navigate = useNavigate();

   const handleRowClick = () => {
-    navigate(`/proposal/${proposal.id}`);
+    navigate(`/proposals/${proposal.id}`);
   };

   return (
```

Any objection? I'd prefer to do it today before people start sharing links to proposals tomorrow.

**Comment by jasonaowen** [comment]
I weakly prefer our current form - as evidenced by the fact I wrote it this way, haha - but don't have a strong opinion. If this is important to you, @reefdog, go for it!

**Comment by reefdog** [comment]
🙏 Thanks for the flexibility! I do have a preference that is, well, stronger than yours it sounds like. 😆 Do you want to thread this into #49's fixup, or should I pin it to the end, or…?

**Comment by jasonaowen** [comment]
Please hold off on touching that branch; I'm in the middle of cleaning it up! Go ahead and open a new PR, and I'll review & rebase after it lands.
