### ISSUE TITLE
Use PDC logo for favicon

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#71]
We've been marketing React too long, it's time for our own brand in the tab!

It should be our little shield logo, naturally.

- https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs
- https://web.dev/building-an-adaptive-favicon/

**Comment by jasonaowen** [comment]
Is this waiting on #26? Or, who can provide this asset?

**Comment by reefdog** [comment]
@jasonaowen Me! I'll do this.

**Comment by reefdog** [comment]
@jasonaowen (Our existing PNGs are plenty high-fidelity for me to generate favicons from.)
