### ISSUE TITLE
Go to Dashboard after initial login

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#75]
When an unauthenticated user tries to access an authenticated page, they're routed to Keycloak and then back to the original requested page upon successful login. 👍

The one exception to this, however, should be the root. When users visit the home page and log in, we should send them to the Dashboard (`/proposals` currently).

Can this be special-cased?

**Comment by jasonaowen** [comment]
Yes; I believe the only two (visible) login links are currently shown on the root page, so we can change where those buttons send you.

**Comment by reefdog** [comment]
@jasonaowen Oh! Are you suggesting that we point the "Login" buttons to the post-login-destination page (i.e., `/proposals`)? That's an interesting solution that would achieve the end result with no change to the callback logic. So we would just change [lines like this](https://github.com/PhilanthropyDataCommons/data-viewer/blob/6e2d7b0332c0951c85d51ab6d9ebccfc6a16f3c5/src/pages/Landing.tsx#L44) to `login('/proposals')`?

**Comment by jasonaowen** [comment]
@reefdog yep indeed; see #79!

**Comment by reefdog** [comment]
Ah-hah, just saw that email come in. 😆 Quick work!
