### ISSUE TITLE
Enable search

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/data-viewer#83]
We want to allow searching proposals. Previously, we introduced a non-functional search box in #49, intended to promise future functionality. This issue is for implementing that functionality, and is the front-end counterpart to https://github.com/PhilanthropyDataCommons/service/issues/277 .

**Comment by jasonaowen** [comment]
In order to meet some demo deadlines, and while the API implementation is being figured out, as a first draft we will implement a front-end, filter-based "search". This takes advantage of the fact that we're not yet doing pagination (see #15), and instead just loading [the first 1,000 proposals](https://github.com/PhilanthropyDataCommons/data-viewer/blob/c908f0208c5dfb2aa190be9d66ce0471236fb52b/src/pages/ProposalList.tsx#L45). To restate that in another way, we cannot have both front-end filter search and pagination at the same time, and we are choosing to prioritize search. Once the API supports searching, we will switch to that, and be able to implement pagination.

**Comment by jasonaowen** [comment]
We got client-side search in #84, but I'm leaving this open until we get server-side search finished.

**Comment by reefdog** [comment]
@jasonaowen I think this can be closed now, right?

**Comment by jasonaowen** [comment]
Oops! Yes, this should have been resolved by #111.
