### ISSUE TITLE
Click handler prevents text selection on proposal table

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#85]
Users should be able to select text on the proposal table without triggering a click / navigating to a proposal. Currently, the click fires even if the user is trying to select text.

**To replicate:**
1. Go to the proposal table
2. Attempt to select text using the mouse cursor (mousedown, drag, mouseup)
3. What should happen: when you release the cursor, you should still be on the proposal table with text selected 
4. What does happen: when you release the cursor, the proposal opens

**Comment by jasonaowen** [comment]
Maybe relatedly, if we want to start linkifying URLs on the proposal list table, clicking those will need to go to the URL rather than to the proposal detail.

**Comment by reefdog** [comment]
@jasonaowen That one should be fairly easy to handle; we'd make sure clicks on those links cancel event propagation so it didn't bubble up to the row, where we capture/handle the proposal-opening.
