### ISSUE TITLE
Set up CD

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#9]
After choosing a host (#8), we'll want to configure CD so that code is automatically deployed. I like Netlify's ability to spin up deployment preview URLs for each new pull request.

We've not discussed the QA or production deployment workflow and I'll bet @jasonaowen has better ideas than me. If it's possible to do something like the following, I think it's ideal:

- PRs auto-deploy to PR-specific domains (definitely doable)
- `main` auto-deploys to a stable development/QA domain
- Releases auto-deploy to production

**Comment by jasonaowen** [comment]
I've got Netlify set up, and we now have DNS: https://pilot.philanthropydatacommons.org/ !
